### ISSUE TITLE
HTML report

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/css-minifier-tests#1]
Need a way to show these results in-browser. CLI option works but is fiddly and requires people to clone this repo, `npm install` and then run the tests. It should be more readily available.

**Comment by caub** [comment]
Nice work on cssnano, I did a simple one recently https://caub.github.io/css-min-bench

I see your benchmark is interesting, with maybe more stats, and on small refined samples with expected result. That's interesting to see it can perform well on small precise sample and on big ones
